dist: trusty
language: java
jdk:
  - oraclejdk8
script:
  - ./client/build.sh
notifications:
  slack: testprioritisation:b88gEuUpTCwV7zTZKYcdUMz8
  email:
    recipients:
      - dpaterson1@sheffield.ac.uk
    on_success: change
    on_failure: change
      
