language: java
jdk:
  - oraclejdk8
before_install:
  - git clone --depth=1 https://github.com/thomasdeanwhite/scythe.git
  - pushd instrumentation
  - git fetch --all
  - git branch dev
  - git checkout dev
  - git pull origin dev
  - mvn clean install
  - popd
script:
  - mvn test package
notifications:
  slack: testprioritisation:b88gEuUpTCwV7zTZKYcdUMz8
  email:
    recipients:
      - dpaterson1@sheffield.ac.uk
    on_success: change
    on_failure: change
      
