language: java
jdk:
  - oraclejdk8
before_install:
  - git clone --depth=1 https://github.com/thomasdeanwhite/scythe.git
  - pushd scythe
  - git fetch --all
  - git branch dev
  - git checkout dev
  - git pull origin dev
  - mvn clean install
  - popd
  - cd client
  - mvn install:install-file -Dfile=lib/com.gzoltar.core-0.0.1-SNAPSHOT.201806211106.jar -DgroupId=com.gzoltar -DartifactId=com.gzoltar.core -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DlocalRepositoryPath=lib
script:
  - mvn test package
notifications:
  slack: testprioritisation:b88gEuUpTCwV7zTZKYcdUMz8
  email:
    recipients:
      - dpaterson1@sheffield.ac.uk
    on_success: change
    on_failure: change
      
